#pragma once

extern PL_KILLCOLLI DEATHZONES_GnorcCove00[];

extern PL_KILLCOLLI DEATHZONES_TownSquare00[];
extern PL_KILLCOLLI DEATHZONES_TownSquare01[];

extern PL_KILLCOLLI DEATHZONES_TreeTops00[];
extern PL_KILLCOLLI DEATHZONES_TreeTops01[];